#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ]

### PULL DATA ###
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone git@github.com:okazhiko/bashcms2_contents.git
chown www-data:www-data "$contentsdir" -R
